name: quiz_app
description: "A new Flutter project."


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'



dependencies:
  flutter:
    sdk: flutter

  # Style
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1

  # Navigation
  go_router: ^14.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Black.ttf
        - weight: 900
        - asset: assets/fonts/poppins/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
        - weight: 800
        - asset: assets/fonts/poppins/Poppins-ExtraBoldItalic.ttf
        - weight: 800
          style: italic
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
        - weight: 700
        - asset: assets/fonts/poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
        - weight: 600
        - asset: assets/fonts/poppins/Poppins-MediumItalic.ttf
        - weight: 600
          style: italic
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
        - weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBoldItalic.ttf
        - weight: 500
          style: italic
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - weight: 400
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
        - weight: 400
          style: italic
